[package]
name = "key_value_store_ssd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
log = "0.4.20"
tokio = { version = "1.4.0", features = ["full"] }